checks:
  argument-count:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30

exclude_patterns:
- "**/*.spec.js"
- "**/*.spec.ts"
- "docs/**/*.js"
- "**/test/**/*.js"
- "packages/wasm-data-wasm/src/fflate.ts"
