// Copyright 2017-2022 @polkadot/wasm-data-asmjs authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/wasm-data-asmjs', path: 'auto', type: 'auto', version: '6.0.2-8' };
