// Copyright 2017-2025 @polkadot/wasm-util authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/wasm-util', path: 'auto', type: 'auto', version: '7.4.2-4-x' };
