// Copyright 2017-2023 @polkadot/wasm-util authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/wasm-util', path: 'auto', type: 'auto', version: '7.0.4-4-x' };
