name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test', 'build', 'deno']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - name: ${{ matrix.step }}
      if: always()
      continue-on-error: true
      run: |
        yarn install --immutable | grep -v 'YN0013'
        if [ "${{ matrix.step }}" != "lint" ]; then
          ./scripts/install-build-deps.sh
        fi
        yarn polkadot-dev-deno-map
        yarn ${{ matrix.step }}
