name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.step }}
      if: always()
      run: |
        yarn install --immutable | grep -v 'YN0013'
        if [ "${{ matrix.step }}" != "lint" ]; then
          ./scripts/install-build-deps.sh
        fi
        yarn ${{ matrix.step }}
